---
title: "Compare behavioral data"
author: "Yuchao Wang"
date: "9/22/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Compare behavioral questionnaires between fMRI and Rating groups} 
library(readxl)
QualtricsGroup <- read_excel("~/Desktop/QualtricsGroup.xlsx")

for (i in 1:nrow(QualtricsGroup)) {
  for (j in 4:27) {
    if ((QualtricsGroup[i,j] >= 0) & (QualtricsGroup[i,j] <= 25)) {
      QualtricsGroup[i,j] <- as.integer(1) 
    }
    else if ((QualtricsGroup[i,j] > 25) & (QualtricsGroup[i,j] <= 50)) {
      QualtricsGroup[i,j] <- as.integer(2) 
    }
    else if ((QualtricsGroup[i,j] > 50) & (QualtricsGroup[i,j] <= 75)) {
      QualtricsGroup[i,j] <- as.integer(3) 
    }
    else if ((QualtricsGroup[i,j] > 75) & (QualtricsGroup[i,j] <= 100)) {
      QualtricsGroup[i,j] <- as.integer(4) 
    }
    # else if (QualtricsGroup[i,j] == 25) {
    #   if (sample(c(TRUE, FALSE),1)) {
    #     QualtricsGroup[i,j] <- as.integer(1)
    #   }
    #   else {
    #     QualtricsGroup[i,j] <- as.integer(2)
    #   }
    # }
    # else if (QualtricsGroup[i,j] == 50) {
    #   if (sample(c(TRUE, FALSE),1)) {
    #     QualtricsGroup[i,j] <- as.integer(2)
    #   }
    #   else {
    #     QualtricsGroup[i,j] <- as.integer(3)
    #   }
    # }
    # else if (QualtricsGroup[i,j] == 75) {
    #   if (sample(c(TRUE, FALSE),1)) {
    #     QualtricsGroup[i,j] <- as.integer(3)
    #   }
    #   else {
    #     QualtricsGroup[i,j] <- as.integer(4)
    #   }
    # }
  }
}

write.csv(QualtricsGroup, file = "~/Desktop/QualtricsGroup_converted.csv")

QnnMeasures <- read.csv(file = "~/Desktop/QualtricsGroup_converted.csv")

library(ggplot2)
library(ggpubr)
ggline(QnnMeasures, x = "group", y = "easy.to.understand", color = "Story",
       add = c("mean_se", "jitter"),
       palette = c("#00AFBB", "#E7B800"))

ggline(QnnMeasures, x = "group", y = "beautiful", color = "Story",
       add = c("mean_se", "jitter"),
       palette = c("#00AFBB", "#E7B800"))

mean(QnnMeasures$beautiful[QnnMeasures$Story=="DM" & QnnMeasures$group=="fmri"], na.rm = TRUE)

aovinterest <- aov(interesting ~ group + Story, data = QnnMeasures)
summary(aovinterest)

for (i in c("EmoEng_1", "EmoEng_2")) {
  a <- t.test(QnnMeasures$i[QnnMeasures$group=="fmri"],QnnMeasures$i[QnnMeasures$group=="qualtrics"])
  print(a)
}

multi.tests <- function(fun = t.test, df, vars, group.var, ...) {
    sapply(simplify = FALSE,                                    # sapply(simplify=T) better, elements named
           vars,                                                # loop on vector of outcome variable names
           function(var) {
               formula <- as.formula(paste(var, "~", group.var))# create a formula with outcome and grouping var.
               fun(data = df, formula, ...)                     # perform test with a given fun, default t.test
           }
           )
}
library(broom)


res.multi.t.tests <-
    multi.tests(fun = t.test,
                df = QnnMeasures,
                vars = c("EmoEng_1","EmoEng_2"),
                group.var = "group",
                var.equal = TRUE, 
                na.rm = TRUE)
res.multi.t.tests

library(readxl)
DM_behav <- read_excel("~/Desktop/DM_behav.xlsx")
DH_behav <- read_excel("~/Desktop/DH_behav.xlsx")

library(dplyr)
DM_behav_res <- data.frame()
DM_behav_res <- rbind(DM_behav_res, do(DM_behav, tidy(t.test(.$`fascinating` ~ .$group,
                 alternative = "two.sided",
                 mu = 0,
                 paired = FALSE,
                 var.equal = FALSE,
                 conf.level = 0.95
                 ))))

write.csv(DM_behav_res, file = "~/Desktop/DM_behav_res_Emothenimgthen10item.csv")
write.csv(DH_behav_res, file = "~/Desktop/DH_behav_res_Emothenimgthen10itemthenficandnovel.csv")
t.test(DM_behav$EmoEng_1[DM_behav$group == "fmri"], DM_behav$EmoEng_1[DM_behav$group == "qualtrics"])
```

```{r cronbach's alpha}
library(ltm)
QnnMeasures <- read.csv(file = "~/Desktop/AesLit Manuscript/QualtricsGroup_converted.csv")


#cronbach's alpha for AesAppreciation DH in rating group 
AesAppreciation_DH_rating <- subset(QnnMeasures, group == "qualtrics" & Story == "DH", select = 5:12)
cronbach.alpha(AesAppreciation_DH_rating)

#cronbach's alpha for AesAppreciation DM in rating group 
AesAppreciation_DM_rating <- subset(QnnMeasures, group == "qualtrics" & Story == "DM", select = 5:12)
cronbach.alpha(AesAppreciation_DM_rating)

#cronbach's alpha for AesAppreciation DH in fmri group 
#excluded items "emotion" and "sad" as the rating group did not rate these two items
AesAppreciation_DH_fmri <- subset(QnnMeasures, group == "fmri" & Story == "DH", select = 5:12)
cronbach.alpha(AesAppreciation_DH_fmri[complete.cases(AesAppreciation_DH_fmri),])#one fmri participant missed AesAppreciation ratings for story DH

#cronbach's alpha for AesAppreciation DM in fmri group 
#excluded items "emotion" and "sad" as the rating group did not rate these two items
AesAppreciation_DM_fmri <- subset(QnnMeasures, group == "fmri" & Story == "DM", select = 5:12)
cronbach.alpha(AesAppreciation_DM_fmri)

#cronbach's alpha for SWAS DH in rating group 
SWAS_DH_rating <- subset(QnnMeasures, group == "qualtrics" & Story == "DH", select = 15:29)
cronbach.alpha(SWAS_DH_rating)

#cronbach's alpha for SWAS DM in rating group 
SWAS_DM_rating <- subset(QnnMeasures, group == "qualtrics" & Story == "DM", select = 15:29)
cronbach.alpha(SWAS_DM_rating)

#cronbach's alpha for SWAS DH in fmri group 
SWAS_DH_fmri <- subset(QnnMeasures, group == "fmri" & Story == "DH", select = 15:29)
cronbach.alpha(SWAS_DH_fmri)

#cronbach's alpha for SWAS DM in fmri group 
SWAS_DM_fmri <- subset(QnnMeasures, group == "fmri" & Story == "DM", select = 15:29)
cronbach.alpha(SWAS_DM_fmri)


```
