---
title: "MatchTiming"
author: "Yuchao Wang"
date: "8/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r pressure, echo=FALSE}

#READ IN ALL 4 ADJUSTED PRAAT WORD ONSETS AND DURATIONS
colLabel <- c("Word", "Onset", "Duration")
DHO <- read.delim("thesis/De Hond_O_adjusted.csv", header = FALSE, sep = ",", stringsAsFactors = FALSE)
DHO <- DHO[-c(1:3), ] #get rid of title
colnames(DHO) <- colLabel

DMO <- read.delim("thesis/De Muur_O_adjusted.csv", header = FALSE, sep = ",", stringsAsFactors = FALSE)
DMO <- DMO[-c(1,2), ] #get rid of title
colnames(DMO) <- colLabel

DH2V <- read.delim("thesis/De Hond_2V_adjusted.csv", header = FALSE, sep = ",", stringsAsFactors = FALSE)
DH2V <- DH2V[-c(1:3), ] #get rid of title
colnames(DH2V) <- colLabel

DM2V <- read.delim("thesis/De Muur_2V_adjusted.csv", header = FALSE, sep = ",", stringsAsFactors = FALSE)
DM2V <- DM2V[-c(1,2), ] #get rid of title
colnames(DM2V) <- colLabel
#--------------------------------------------------

#MATCH, FOR ORIGINAL(FIRST PERSON PERSPEC), THE TIMING WITH RATED WORDS

#SETUP 
emoResultClean <- readRDS("emoResultClean.rds")
litResultClean <- readRDS("litResultClean.rds")

colNumEmo <- ncol(emoResultClean)
colNumLit <- ncol(litResultClean)

emoOGwTiming <- emoResultClean
emo2VwTiming <- emoResultClean
litOGwTiming <- litResultClean
lit2VwTiming <- litResultClean

  #EMO
for (index in 1:1237) {
  if (grepl(DHO[index,1], emoResultClean[index,1], fixed = TRUE)) {
    emoOGwTiming[index, c(colNumEmo+1, colNumEmo+2)] <- DHO[index, c(2,3)]
  }
  else {
    emoOGwTiming[index, c(colNumEmo+1, colNumEmo+2)] <- c("mismatch", "mismatch")
  }
}

for (index in 1:1117) {
  if (grepl(DMO[index,1], emoResultClean[index + 1237,1], fixed = TRUE)) {
    emoOGwTiming[index + 1237, c(colNumEmo+1, colNumEmo+2)] <- DMO[index, c(2,3)]
  }
  else {
    emoOGwTiming[index + 1237, c(colNumEmo+1, colNumEmo+2)] <- c("mismatch", "mismatch")
  }
}

  #LIT
for (index in 1:1237) {
  if (grepl(DHO[index,1], litResultClean[index,1], fixed = TRUE)) {
    litOGwTiming[index, c(colNumLit+1, colNumLit+2)] <- DHO[index, c(2,3)]
  }
  else {
    litOGwTiming[index, c(colNumLit+1, colNumLit+2)] <- c("mismatch", "mismatch")
  }
}

for (index in 1:1117) {
  if (grepl(DMO[index,1], litResultClean[index + 1237,1], fixed = TRUE)) {
    litOGwTiming[index + 1237, c(colNumLit+1, colNumLit+2)] <- DMO[index, c(2,3)]
  }
  else {
    litOGwTiming[index + 1237, c(colNumLit+1, colNumLit+2)] <- c("mismatch", "mismatch")
  }
}
#-------------------------------------------------- 


#MATCH, FOR 2V(THIRD PERSON PERSPEC), THE TIMING WITH RATED WORDS
  #EMO
for (index in 1:1237) {
  if (grepl(DH2V[index,1], emoResultClean[index,1], fixed = TRUE)) {
    emo2VwTiming[index, c(colNumEmo+1, colNumEmo+2)] <- DH2V[index, c(2,3)]
  }
  else {
    emo2VwTiming[index, c(colNumEmo+1, colNumEmo+2)] <- c("mismatch", "mismatch")
  }
}

for (index in 1:1117) {
  if (grepl(DM2V[index,1], emoResultClean[index + 1237,1], fixed = TRUE)) {
    emo2VwTiming[index + 1237, c(colNumEmo+1, colNumEmo+2)] <- DM2V[index, c(2,3)]
  }
  else {
    emo2VwTiming[index + 1237, c(colNumEmo+1, colNumEmo+2)] <- c("mismatch", "mismatch")
  }
}

  #LIT
for (index in 1:1237) {
  if (grepl(DH2V[index,1], litResultClean[index,1], fixed = TRUE)) {
    lit2VwTiming[index, c(colNumLit+1, colNumLit+2)] <- DH2V[index, c(2,3)]
  }
  else {
    lit2VwTiming[index, c(colNumLit+1, colNumLit+2)] <- c("mismatch", "mismatch")
  }
}

for (index in 1:1117) {
  if (grepl(DM2V[index,1], litResultClean[index + 1237,1], fixed = TRUE)) {
    lit2VwTiming[index + 1237, c(colNumLit+1, colNumLit+2)] <- DM2V[index, c(2,3)]
  }
  else {
    lit2VwTiming[index + 1237, c(colNumLit+1, colNumLit+2)] <- c("mismatch", "mismatch")
  }
}
#-------------------------------------------------- 


#WRITE OUTPUT FILES
emoDHOFinal <- matrix(data = NA, nrow = 0, ncol = colNumEmo+2)
emoDMOFinal <- matrix(data = NA, nrow = 0, ncol = colNumEmo+2)
emoDH2VFinal <- matrix(data = NA, nrow = 0, ncol = colNumEmo+2)
emoDM2VFinal <- matrix(data = NA, nrow = 0, ncol = colNumEmo+2)
litDHOFinal <- matrix(data = NA, nrow = 0, ncol = colNumLit+2)
litDMOFinal <- matrix(data = NA, nrow = 0, ncol = colNumLit+2)
litDH2VFinal <- matrix(data = NA, nrow = 0, ncol = colNumLit+2)
litDM2VFinal <- matrix(data = NA, nrow = 0, ncol = colNumLit+2)

#EMO
  #Original Versions
for (index in 1:1237) {
  if ((emoOGwTiming[index, colNumEmo+2] == "mismatch") | (emoOGwTiming[index, colNumEmo+2] == "0")) {
    next
  }
  else {
    emoDHOFinal <- rbind(emoDHOFinal, emoOGwTiming[index, ])
  }
}
write.csv(emoDHOFinal, file = "thesis/emoDHOFinal.csv")


for (index in 1:1117) {
  if ((emoOGwTiming[index+1237, colNumEmo+2] == "mismatch") | (emoOGwTiming[index+1237, colNumEmo+2] == "0")) {
    next
  }
  else {
    emoDMOFinal <- rbind(emoDMOFinal, emoOGwTiming[index, ])
  }
}
write.csv(emoDMOFinal, file = "thesis/emoDMOFinal.csv")

  #2V(third pers perspec)
for (index in 1:1237) {
  if ((emo2VwTiming[index, colNumEmo+2] == "mismatch") | (emo2VwTiming[index, colNumEmo+2] == "0")) {
    next
  }
  else {
    emoDH2VFinal <- rbind(emoDH2VFinal, emo2VwTiming[index, ])
  }
}
write.csv(emoDH2VFinal, file = "thesis/emoDH2VFinal.csv")

for (index in 1:1117) {
  if ((emo2VwTiming[index+1237, colNumEmo+2] == "mismatch") | (emo2VwTiming[index+1237, colNumEmo+2] == "0")) {
    next
  }
  else {
    emoDM2VFinal <- rbind(emoDM2VFinal, emo2VwTiming[index, ])
  }
}
write.csv(emoDM2VFinal, file = "thesis/emoDM2VFinal.csv")

#LIT
  #Original Versions
for (index in 1:1237) {
  if ((litOGwTiming[index, colNumLit+2] == "mismatch") | (litOGwTiming[index, colNumLit+2] == "0")) {
    next
  }
  else {
    litDHOFinal <- rbind(litDHOFinal, litOGwTiming[index, ])
  }
}
write.csv(litDHOFinal, file = "thesis/litDHOFinal.csv")


for (index in 1:1117) {
  if ((litOGwTiming[index+1237, colNumLit+2] == "mismatch") | (litOGwTiming[index+1237, colNumLit+2] == "0")) {
    next
  }
  else {
    litDMOFinal <- rbind(litDMOFinal, litOGwTiming[index, ])
  }
}
write.csv(litDMOFinal, file = "thesis/litDMOFinal.csv")

  #2V(third pers perspec)
for (index in 1:1237) {
  if ((lit2VwTiming[index, colNumLit+2] == "mismatch") | (lit2VwTiming[index, colNumLit+2] == "0")) {
    next
  }
  else {
    litDH2VFinal <- rbind(litDH2VFinal, lit2VwTiming[index, ])
  }
}
write.csv(litDH2VFinal, file = "thesis/litDH2VFinal.csv")

for (index in 1:1117) {
  if ((lit2VwTiming[index+1237, colNumLit+2] == "mismatch") | (lit2VwTiming[index+1237, colNumLit+2] == "0")) {
    next
  }
  else {
    litDM2VFinal <- rbind(litDM2VFinal, lit2VwTiming[index, ])
  }
}
write.csv(litDM2VFinal, file = "thesis/litDM2VFinal.csv")


```