---
title: "MatchTiming"
author: "Yuchao Wang"
date: "8/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r matchPraatFiles, echo=FALSE}
#READ IN ALL 4 ADJUSTED PRAAT WORD ONSETS AND DURATIONS----
colLabel <- c("Word", "Onset", "Duration")
DHO <- read.delim("thesis/De Hond_O_adjusted.csv", header = FALSE, sep = ",", stringsAsFactors = FALSE)
DHO <- DHO[-c(1:3), ] #get rid of title
colnames(DHO) <- colLabel

DMO <- read.delim("thesis/De Muur_O_adjusted.csv", header = FALSE, sep = ",", stringsAsFactors = FALSE)
DMO <- DMO[-c(1,2), ] #get rid of title
colnames(DMO) <- colLabel

DH2V <- read.delim("thesis/De Hond_2V_adjusted.csv", header = FALSE, sep = ",", stringsAsFactors = FALSE)
DH2V <- DH2V[-c(1:3), ] #get rid of title
colnames(DH2V) <- colLabel

DM2V <- read.delim("thesis/De Muur_2V_adjusted.csv", header = FALSE, sep = ",", stringsAsFactors = FALSE)
DM2V <- DM2V[-c(1,2), ] #get rid of title
colnames(DM2V) <- colLabel

#MATCH, FOR ORIGINAL(FIRST PERSON PERSPEC), THE TIMING WITH RATED WORDS----

#SETUP 
emoResultClean <- readRDS("emoResultClean.rds")
litResultClean <- readRDS("litResultClean.rds")

colNumEmo <- ncol(emoResultClean)
colNumLit <- ncol(litResultClean)

emoOGwTiming <- emoResultClean
emo2VwTiming <- emoResultClean
litOGwTiming <- litResultClean
lit2VwTiming <- litResultClean


addTimingCols <- function(totalWord, praatClean, resultClean, resultwTiming, colNum) {
  if (totalWord == 1237) {
     for (index in 1:totalWord) {
        if (grepl(praatClean[index,1], resultClean[index,1], fixed = TRUE)) {
          resultwTiming[index, c(colNum+1, colNum+2)] <- praatClean[index, c(2,3)]
        }
        else {
          resultwTiming[index, c(colNum+1, colNum+2)] <- c("mismatch", "mismatch")
        }
     }
  }
  else {
    for (index in 1:totalWord) {
      if (grepl(praatClean[index,1], resultClean[index + 1237,1], fixed = TRUE)) {
        resultwTiming[index + 1237, c(colNum+1, colNum+2)] <- praatClean[index, c(2,3)]
      }
      else {
        resultwTiming[index + 1237, c(colNum+1, colNum+2)] <- c("mismatch", "mismatch")
      }
    }
  }
  return(resultwTiming)
}

emoOGwTiming <- addTimingCols(1237, DHO, emoResultClean, emoOGwTiming, colNumEmo)
emoOGwTiming <- addTimingCols(1117, DMO, emoResultClean, emoOGwTiming, colNumEmo)
litOGwTiming <- addTimingCols(1237, DHO, litResultClean, litOGwTiming, colNumLit)
litOGwTiming <- addTimingCols(1117, DMO, litResultClean, litOGwTiming, colNumLit)
emo2VwTiming <- addTimingCols(1237, DH2V, emoResultClean, emo2VwTiming, colNumEmo)
emo2VwTiming <- addTimingCols(1117, DM2V, emoResultClean, emo2VwTiming, colNumEmo)
lit2VwTiming <- addTimingCols(1237, DH2V, litResultClean, lit2VwTiming, colNumLit)
lit2VwTiming <- addTimingCols(1117, DM2V, litResultClean, lit2VwTiming, colNumLit)


stderr <- function(x) {
  sd(x, na.rm = TRUE)/sqrt(length(x[!is.na(x)]))
}

addMNSECol <- function(resultwTiming, colNum) {
  for (colIndex in 3: colNum) { 
    resultwTiming[, colIndex] <- as.numeric(resultwTiming[, colIndex])
  }
  resultwTiming <- transform(resultwTiming, MN = rowMeans(resultwTiming[ ,3:colNum], na.rm = TRUE))
  rowNum <- nrow(resultwTiming)
  for (rowIndex in 1:rowNum) {
    resultwTiming[rowIndex, colNum+4] <- stderr(resultwTiming[rowIndex, 3:colNum])
  }
  names(resultwTiming)[colNum+4] <- 'SE'
  return(resultwTiming)
}

emoOGwTiming <- addMNSECol(emoOGwTiming, colNumEmo)
emo2VwTiming <- addMNSECol(emo2VwTiming, colNumEmo)
litOGwTiming <- addMNSECol(litOGwTiming, colNumLit)
lit2VwTiming <- addMNSECol(lit2VwTiming, colNumLit)



#WRITE OUTPUT FILES
emoDHOFinal <- matrix(data = NA, nrow = 0, ncol = colNumEmo+4)
emoDMOFinal <- matrix(data = NA, nrow = 0, ncol = colNumEmo+4)
emoDH2VFinal <- matrix(data = NA, nrow = 0, ncol = colNumEmo+4)
emoDM2VFinal <- matrix(data = NA, nrow = 0, ncol = colNumEmo+4)
litDHOFinal <- matrix(data = NA, nrow = 0, ncol = colNumLit+4)
litDMOFinal <- matrix(data = NA, nrow = 0, ncol = colNumLit+4)
litDH2VFinal <- matrix(data = NA, nrow = 0, ncol = colNumLit+4)
litDM2VFinal <- matrix(data = NA, nrow = 0, ncol = colNumLit+4)

cleanOutput <- function(totalWord, colNum, rawData, outputFile, outputName) {
  if (totalWord == 1237) {
    for (index in 1:totalWord) {
      if ((rawData[index, colNum+2] == "mismatch") | (rawData[index, colNum+2] == "0")) {
        next
      }
      else {
        outputFile <- rbind(outputFile, rawData[index, ])
      }
    }
  }
  else {
    for (index in 1:totalWord) {
      if ((rawData[index+1237, colNum+2] == "mismatch") | (rawData[index+1237, colNum+2] == "0")) {
        next
      }
      else {
        outputFile <- rbind(outputFile, rawData[index+1237, ])
      }
    }
  }
  #str(outputFile)
  write.csv(outputFile, file = paste("thesis/", outputName, ".csv", sep=""))
  return(outputFile)
}
#This function cleans mismatched entries and write CSV output files. 

emoDHOFinal <- cleanOutput(1237, colNumEmo, emoOGwTiming, emoDHOFinal, "emoDHOFinal")
emoDMOFinal <- cleanOutput(1117, colNumEmo, emoOGwTiming, emoDMOFinal, "emoDMOFinal")
emoDH2VFinal <- cleanOutput(1237, colNumEmo, emo2VwTiming, emoDH2VFinal, "emoDH2VFinal")
emoDM2VFinal <- cleanOutput(1117, colNumEmo, emo2VwTiming, emoDM2VFinal, "emoDM2VFinal")
litDHOFinal <- cleanOutput(1237, colNumLit, litOGwTiming, litDHOFinal, "litDHOFinal")
litDMOFinal <- cleanOutput(1117, colNumLit, litOGwTiming, litDMOFinal, "litDMOFinal")
litDH2VFinal <- cleanOutput(1237, colNumLit, lit2VwTiming, litDH2VFinal, "litDH2VFinal")
litDM2VFinal <- cleanOutput(1117, colNumLit, lit2VwTiming, litDM2VFinal, "litDM2VFinal")

```

```{r interactivePlotsAttempt, eval=FALSE}
library(ggplot2)
library(plotly)
plot(emoDHOFinal$Onset, emoDHOFinal$MN)
p <- ggplot(litDHOFinal, aes(x = Onset, y = MN)) +
  geom_point() #+ 
  #geom_errorbar(emoDHOFinal, mapping=aes(x = Onset, ymin = MN-SE, ymax=MN+SE)
ggplotly(p)

dotWithErrorPlotSave <- function(finalData) { 
  #dodge <- position_dodge(width = 0.9)
  limits <- aes(ymax = finalData$MN + finalData$SE, 
                ymin = finalData$MN - finalData$SE)
 p <- ggplot(data = finalData, aes(x = Onset, y = MN, color = "blue")) + 
    geom_point(size=2.5, alpha=0.6, color = "orange") +
    geom_errorbar(limits, width = 0.25) +
    theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), 
          axis.title.x=element_blank()) + 
    ggtitle(paste("emoDH", ", N=", ncol(finalData)-6, sep=""))
 # ggsave(paste("~/Desktop/", shortTitle,".png", sep = ""), plot = last_plot(), device = png(),
#    scale = 1, width = 300, height = 200, units = c("mm"),
 #   dpi = 300, limitsize = TRUE)
  return(p)
}

dotWithErrorPlotSave(emoDHOFinal)

```

