---
title: "Ratings matching original words"
author: "Yuchao Wang"
date: "8/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
```

```{r Clean up raw ratings, echo = FALSE}
#Clean up delimited csv files containing all rated words in survey----
template <- read.csv(file = "forWordSeparation_cleaned.csv", header = F, sep = ",", stringsAsFactors = FALSE)
template <- t(template) 
colnames(template) <- template[1, ] 
template <- template[-1, ]
template <- as.data.frame(template) #data type converted to matrix after transpose, due to rectangular shape - force back into data frame for "gather"
template <- gather(template, "qnLabel", "word", 1:17)
template <- template[!(template$word == ""), ] 
template <- template[ , c("word","qnLabel")]
template$qnLabel <- trimws(template$qnLabel)
template$qnLabel <- as.factor(template$qnLabel)
template$qnLabel <- factor(template$qnLabel, levels = c("3.1","5.1","7.1","9.1","11.1","13.1","15.1","17.1","19.1","24.1","26.1","28.1","30.1","32.1","34.1","36.1","38.1")) 
qnLabel <- levels(template$qnLabel)


#Match emo results----    
emoResult <- read.csv(file="Verhalen_Emotional+Arousal_October+1%2C+2019_13.27.csv", 
                  header = TRUE, sep = ",", stringsAsFactors = FALSE)
emoResult <- emoResult[-c(1,2), ] #get rid of title row
emoResult <- emoResult[-c(1:9), ] #get rid of preview Test results
emoResult <- emoResult[-c(15:17,28), ] #get rid of incomplete results


totalParticipant <- nrow(emoResult)
totalWord <- nrow(template)
emoResultClean <- template


for (indexResponse in 1:totalParticipant) {
  for (indexWord in 1:totalWord) {
    searchWord <- template[indexWord,1]
    searchQn <- template[indexWord,2]
    resultCol <- indexResponse+2
    emoResultClean[indexWord,resultCol] <- NA #initialize a new column
      for (possibleRating in 1:7) {
        if (!is.na(emoResultClean[indexWord,resultCol])) {
          break
        }
        currentColName <- paste ("Q", searchQn, "_", possibleRating, sep = "", collapse = NULL)
        if (grepl(searchWord, emoResult[indexResponse,currentColName], fixed = TRUE)) {
            emoResultClean[indexWord,resultCol] <- substr(currentColName, nchar(currentColName), nchar(currentColName))        
        }
        else {
          if ((possibleRating == 7) & (is.na(emoResultClean[indexWord,resultCol]))) {
            emoResultClean[indexWord,resultCol] <- NA
          }
        }
      }
  }
}


#Match lit results----
litResult <- read.csv(file="Verhalen_Literariness_October+1%2C+2019_13.28.csv", 
                  header = TRUE, sep = ",", stringsAsFactors = FALSE)
litResult <- litResult[-c(1,2), ] #get rid of title row
litResult <- litResult[-c(1:10), ] #get rid of preview Test results


totalParticipant <- nrow(litResult)
totalWord <- nrow(template)
litResultClean <- template


for (indexResponse in 1:totalParticipant) {
  for (indexWord in 1:totalWord) {
    searchWord <- template[indexWord,1]
    searchQn <- template[indexWord,2]
    resultCol <- indexResponse+2
    litResultClean[indexWord,resultCol] <- NA #initialize a new column
      for (possibleRating in 1:2) {
        if (!is.na(litResultClean[indexWord,resultCol])) {
          break
        }
        currentColName <- paste ("Q", searchQn, "_", possibleRating, sep = "", collapse = NULL)
        if (grepl(searchWord, litResult[indexResponse,currentColName], fixed = TRUE)) {
            litResultClean[indexWord,resultCol] <- substr(currentColName, nchar(currentColName), nchar(currentColName))        
        }
        else {
          if ((possibleRating == 2) & (is.na(litResultClean[indexWord,resultCol]))) {
            litResultClean[indexWord,resultCol] <- NA
          }
        }
      }
  }
}

#Save clean files---- 
saveRDS(emoResultClean, file = "emoResultClean.rds")
saveRDS(litResultClean, file = "litResultClean.rds")
saveRDS(template, file = "template.rds")

```

```{r Visualization} 
#Visualize ratings----
library(ggplot2)
library(psych)

dotWithErrorPlotSave <- function(trend, tResultClean, plotTitle, shortTitle) { 
  dodge <- position_dodge(width = 0.9)
  limits <- aes(ymax = trend$mean + trend$se, 
                ymin = trend$mean - trend$se)
  ggplot(data = trend, aes(x = vars, y = mean, color = vars)) + 
    geom_point(size=2.5, alpha=0.6, color = "orange") +
    geom_errorbar(limits, position = dodge, width = 0.25) +
    xlab("Word #") +
    theme(text = element_text(size=20), axis.text.x=element_blank(), axis.ticks.x=element_blank()) + 
    ggtitle(paste(plotTitle, ", N=", nrow(tResultClean), sep=""))
  ggsave(paste("~/Desktop/", shortTitle,".png", sep = ""), plot = last_plot(), device = png(),
    scale = 1, width = 300, height = 200, units = c("mm"),
    dpi = 300, limitsize = TRUE)
}
#EMO
temoResultClean <- t(emoResultClean)
temoResultClean <- temoResultClean[-c(1:2),]

emoTrend <- describe(temoResultClean)
emoDHTrend <- emoTrend[c(1:1237),]
emoDMTrend <- emoTrend[c(1238:2354),]
emoDMTrend$vars <- seq(length=nrow(emoDMTrend)) 

dotWithErrorPlotSave(emoDMTrend, temoResultClean, "Emotional Arousal Rating for De Muur", "emoDM")
dotWithErrorPlotSave(emoDHTrend, temoResultClean, "Emotional Arousal Rating for De Mexicaanse Hond", "emoDH")


#LIT
tlitResultClean <- t(litResultClean)
tlitResultClean <- tlitResultClean[-c(1:2),]
litTrend <- describe(tlitResultClean)
litDHTrend <- litTrend[c(1:1237),]
litDMTrend <- litTrend[c(1238:2354),]
litDMTrend$vars <- seq(length=nrow(litDMTrend)) 

dotWithErrorPlotSave(litDMTrend, tlitResultClean, "Literariness Rating for De Muur", "litDM")
dotWithErrorPlotSave(litDHTrend, tlitResultClean, "Literariness Rating for De Mexicaanse Hond", "litDH")


```


```{r Intraclass Correlation}
library(lme4)
emoResultCleanICC <- matrix(data = NA, nrow = 0, ncol = 27)
for (index in 1:2354) {
  emoResultCleanICC <- rbind(emoResultCleanICC, emoResultClean[index, 3:29])
}
for (j in 1:27) {
    emoResultCleanICC[,j] <- as.numeric(emoResultCleanICC[,j])
}
ICC(emoResultCleanICC, missing = FALSE, alpha = 0.05)


litResultCleanICC <- matrix(data = NA, nrow = 0, ncol = 27)
for (index in 1:2354) {
  litResultCleanICC <- rbind(litResultCleanICC, litResultClean[index, 3:29])
}
for (j in 1:27) {
    litResultCleanICC[,j] <- as.numeric(litResultCleanICC[,j])
}
ICC(litResultCleanICC, missing = FALSE, alpha = 0.05)

```



```{r Correlation of Emo~Lit}
#Simple linear regression ANOVA of Emo on Lit ratings, with and without boxcar smoothing 
library('zoo')

emoDHTrend <- cbind(emoDHTrend, rollmean(emoDHTrend$mean, k = 5, fill = NA, align = "center"))
names(emoDHTrend)[14] <- "rollmean"
litDHTrend <- cbind(litDHTrend, rollmean(litDHTrend$mean, k = 5, fill = NA, align = "center"))
names(litDHTrend)[14] <- "rollmean"
emo_lit_DHmodel <- lm(emoDHTrend$mean ~ litDHTrend$mean)
emo_lit_DHboxedmodel <- lm(emoDHTrend$rollmean ~ litDHTrend$rollmean)
anova(emo_lit_DHmodel)
anova(emo_lit_DHboxedmodel)

emoDMTrend <- cbind(emoDMTrend, rollmean(emoDMTrend$mean, k = 5, fill = NA, align = "center"))
names(emoDMTrend)[14] <- "rollmean"
litDMTrend <- cbind(litDMTrend, rollmean(litDMTrend$mean, k = 5, fill = NA, align = "center"))
names(litDMTrend)[14] <- "rollmean"
emo_lit_DMmodel <- lm(emoDMTrend$mean ~ litDMTrend$mean)
emo_lit_DMboxedmodel <- lm(emoDMTrend$rollmean ~ litDMTrend$rollmean)
anova(emo_lit_DMmodel)
anova(emo_lit_DMboxedmodel)
```
